"""per business whatsapp sender

Revision ID: 07fa2f16e0c1
Revises: 27d989c2cda2
Create Date: 2026-08-11 16:52:53.992135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types are rendered by autogenerate as app.db.models.<Type>,
# but the import is not emitted. Without this, every migration that touches a
# timestamp column fails with NameError: name 'app' is not defined.
import app.db.models


# revision identifiers, used by Alembic.
revision: str = '07fa2f16e0c1'
down_revision: Union[str, Sequence[str], None] = '27d989c2cda2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('whatsapp_encrypted_access_token', sa.Text(), server_default='', nullable=False))
    op.add_column('businesses', sa.Column('whatsapp_display_number', sa.String(length=32), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'whatsapp_display_number')
    op.drop_column('businesses', 'whatsapp_encrypted_access_token')
    # ### end Alembic commands ###
