"""platform settings

Revision ID: 27d989c2cda2
Revises: 83292a83e66f
Create Date: 2026-08-10 22:56:58.441477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types are rendered by autogenerate as app.db.models.<Type>,
# but the import is not emitted. Without this, every migration that touches a
# timestamp column fails with NameError: name 'app' is not defined.
import app.db.models


# revision identifiers, used by Alembic.
revision: str = '27d989c2cda2'
down_revision: Union[str, Sequence[str], None] = '83292a83e66f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('encrypted_value', sa.Text(), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', app.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('platform_settings')
    # ### end Alembic commands ###
