"""initial schema

Revision ID: 3005a59fe145
Revises: 
Create Date: 2026-08-10 15:23:51.306514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db.models


# revision identifiers, used by Alembic.
revision: str = '3005a59fe145'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('business_id', sa.String(length=32), nullable=True),
    sa.Column('actor_user_id', sa.String(length=32), nullable=True),
    sa.Column('actor_label', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', app.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_business_created', 'audit_logs', ['business_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_business_id'), 'audit_logs', ['business_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_table('businesses',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('contact_phone', sa.String(length=32), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('business_type', sa.String(length=64), nullable=False),
    sa.Column('business_descriptor', sa.String(length=255), nullable=False),
    sa.Column('labels', sa.JSON(), nullable=False),
    sa.Column('intake_fields', sa.JSON(), nullable=False),
    sa.Column('agent_rules', sa.JSON(), nullable=False),
    sa.Column('escalation_instructions', sa.Text(), nullable=False),
    sa.Column('agent_name', sa.String(length=120), nullable=False),
    sa.Column('phone_number', sa.String(length=32), nullable=False),
    sa.Column('vapi_assistant_id', sa.String(length=120), nullable=False),
    sa.Column('vapi_phone_number_id', sa.String(length=120), nullable=False),
    sa.Column('primary_language', sa.Enum('hi', 'en', 'hi-en', name='language', native_enum=False, length=32), nullable=False),
    sa.Column('greeting_en', sa.Text(), nullable=False),
    sa.Column('greeting_hi', sa.Text(), nullable=False),
    sa.Column('agent_notes', sa.Text(), nullable=False),
    sa.Column('opens_at', sa.Time(), nullable=False),
    sa.Column('closes_at', sa.Time(), nullable=False),
    sa.Column('working_days', sa.JSON(), nullable=False),
    sa.Column('slot_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('whatsapp_enabled', sa.Boolean(), nullable=False),
    sa.Column('whatsapp_phone_number_id', sa.String(length=64), nullable=False),
    sa.Column('reminder_24h_enabled', sa.Boolean(), nullable=False),
    sa.Column('reminder_2h_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('transcript_retention_days', sa.Integer(), nullable=False),
    sa.Column('recording_retention_days', sa.Integer(), nullable=False),
    sa.Column('created_at', app.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_businesses_business_type'), 'businesses', ['business_type'], unique=False)
    op.create_index(op.f('ix_businesses_is_active'), 'businesses', ['is_active'], unique=False)
    op.create_index(op.f('ix_businesses_phone_number'), 'businesses', ['phone_number'], unique=True)
    op.create_index(op.f('ix_businesses_slug'), 'businesses', ['slug'], unique=True)
    op.create_index(op.f('ix_businesses_vapi_assistant_id'), 'businesses', ['vapi_assistant_id'], unique=False)
    op.create_table('appointment_types',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('business_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointment_types_business_id'), 'appointment_types', ['business_id'], unique=False)
    op.create_table('calendar_credentials',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('business_id', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('connected_email', sa.String(length=255), nullable=False),
    sa.Column('calendar_id', sa.String(length=255), nullable=False),
    sa.Column('encrypted_refresh_token', sa.Text(), nullable=False),
    sa.Column('encrypted_access_token', sa.Text(), nullable=False),
    sa.Column('access_token_expires_at', app.db.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('is_connected', sa.Boolean(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.Column('created_at', app.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_credentials_business_id'), 'calendar_credentials', ['business_id'], unique=True)
    op.create_table('customers',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('business_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('preferred_language', sa.Enum('hi', 'en', 'hi-en', name='language', native_enum=False, length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', app.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'phone', name='uq_customer_business_phone')
    )
    op.create_index('ix_customers_business_created', 'customers', ['business_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_customers_business_id'), 'customers', ['business_id'], unique=False)
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=False)
    op.create_table('staff_members',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('business_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('specialization', sa.String(length=255), nullable=False),
    sa.Column('google_calendar_id', sa.String(length=255), nullable=False),
    sa.Column('consultation_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('opens_at', sa.Time(), nullable=True),
    sa.Column('closes_at', sa.Time(), nullable=True),
    sa.Column('working_days', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_staff_business_active', 'staff_members', ['business_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_staff_members_business_id'), 'staff_members', ['business_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('superadmin', 'owner', 'staff', name='userrole', native_enum=False, length=32), nullable=False),
    sa.Column('business_id', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', app.db.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', app.db.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_business_id'), 'users', ['business_id'], unique=False)
    op.create_index('ix_users_business_role', 'users', ['business_id', 'role'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('calls',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('business_id', sa.String(length=32), nullable=False),
    sa.Column('vapi_call_id', sa.String(length=120), nullable=False),
    sa.Column('customer_id', sa.String(length=32), nullable=True),
    sa.Column('caller_number', sa.String(length=32), nullable=False),
    sa.Column('started_at', app.db.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('ended_at', app.db.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('language', sa.Enum('hi', 'en', 'hi-en', name='language', native_enum=False, length=32), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('recording_url', sa.String(length=1024), nullable=False),
    sa.Column('outcome', sa.Enum('booked', 'rescheduled', 'cancelled', 'enquiry', 'no_details', 'failed', name='calloutcome', native_enum=False, length=32), nullable=False),
    sa.Column('cost_paise', sa.Integer(), nullable=False),
    sa.Column('ended_reason', sa.String(length=120), nullable=False),
    sa.Column('created_at', app.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calls_business_id'), 'calls', ['business_id'], unique=False)
    op.create_index('ix_calls_business_outcome', 'calls', ['business_id', 'outcome'], unique=False)
    op.create_index('ix_calls_business_started', 'calls', ['business_id', 'started_at'], unique=False)
    op.create_index(op.f('ix_calls_customer_id'), 'calls', ['customer_id'], unique=False)
    op.create_index(op.f('ix_calls_outcome'), 'calls', ['outcome'], unique=False)
    op.create_index(op.f('ix_calls_vapi_call_id'), 'calls', ['vapi_call_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', app.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', app.db.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('appointments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('business_id', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.String(length=32), nullable=False),
    sa.Column('staff_member_id', sa.String(length=32), nullable=True),
    sa.Column('appointment_type_id', sa.String(length=32), nullable=True),
    sa.Column('call_id', sa.String(length=32), nullable=True),
    sa.Column('starts_at', app.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('ends_at', app.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'rescheduled', 'cancelled', 'completed', 'no_show', name='appointmentstatus', native_enum=False, length=32), nullable=False),
    sa.Column('google_event_id', sa.String(length=255), nullable=False),
    sa.Column('google_calendar_id', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('cancellation_reason', sa.Text(), nullable=False),
    sa.Column('rescheduled_from_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', app.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['appointment_type_id'], ['appointment_types.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_member_id'], ['staff_members.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_business_id'), 'appointments', ['business_id'], unique=False)
    op.create_index('ix_appointments_business_start', 'appointments', ['business_id', 'starts_at'], unique=False)
    op.create_index('ix_appointments_business_status', 'appointments', ['business_id', 'status'], unique=False)
    op.create_index(op.f('ix_appointments_call_id'), 'appointments', ['call_id'], unique=False)
    op.create_index(op.f('ix_appointments_customer_id'), 'appointments', ['customer_id'], unique=False)
    op.create_index(op.f('ix_appointments_google_event_id'), 'appointments', ['google_event_id'], unique=False)
    op.create_index('ix_appointments_reminder_scan', 'appointments', ['status', 'starts_at'], unique=False)
    op.create_index(op.f('ix_appointments_staff_member_id'), 'appointments', ['staff_member_id'], unique=False)
    op.create_index(op.f('ix_appointments_status'), 'appointments', ['status'], unique=False)
    op.create_table('whatsapp_messages',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('business_id', sa.String(length=32), nullable=False),
    sa.Column('appointment_id', sa.String(length=32), nullable=True),
    sa.Column('to_phone', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.Enum('confirmation', 'reminder_24h', 'reminder_2h', 'cancellation', 'reschedule', name='messagekind', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('pending', 'sent', 'delivered', 'read', 'failed', 'cancelled', name='messagestatus', native_enum=False, length=32), nullable=False),
    sa.Column('template_name', sa.String(length=120), nullable=False),
    sa.Column('language_code', sa.String(length=16), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('rendered_preview', sa.Text(), nullable=False),
    sa.Column('scheduled_for', app.db.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('sent_at', app.db.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', app.db.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('wa_message_id', sa.String(length=128), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.Column('created_at', app.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('appointment_id', 'kind', name='uq_wa_appointment_kind')
    )
    op.create_index('ix_wa_business_created', 'whatsapp_messages', ['business_id', 'created_at'], unique=False)
    op.create_index('ix_wa_due', 'whatsapp_messages', ['status', 'scheduled_for'], unique=False)
    op.create_index(op.f('ix_whatsapp_messages_appointment_id'), 'whatsapp_messages', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_messages_business_id'), 'whatsapp_messages', ['business_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_messages_status'), 'whatsapp_messages', ['status'], unique=False)
    op.create_index(op.f('ix_whatsapp_messages_wa_message_id'), 'whatsapp_messages', ['wa_message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_whatsapp_messages_wa_message_id'), table_name='whatsapp_messages')
    op.drop_index(op.f('ix_whatsapp_messages_status'), table_name='whatsapp_messages')
    op.drop_index(op.f('ix_whatsapp_messages_business_id'), table_name='whatsapp_messages')
    op.drop_index(op.f('ix_whatsapp_messages_appointment_id'), table_name='whatsapp_messages')
    op.drop_index('ix_wa_due', table_name='whatsapp_messages')
    op.drop_index('ix_wa_business_created', table_name='whatsapp_messages')
    op.drop_table('whatsapp_messages')
    op.drop_index(op.f('ix_appointments_status'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_staff_member_id'), table_name='appointments')
    op.drop_index('ix_appointments_reminder_scan', table_name='appointments')
    op.drop_index(op.f('ix_appointments_google_event_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_customer_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_call_id'), table_name='appointments')
    op.drop_index('ix_appointments_business_status', table_name='appointments')
    op.drop_index('ix_appointments_business_start', table_name='appointments')
    op.drop_index(op.f('ix_appointments_business_id'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_calls_vapi_call_id'), table_name='calls')
    op.drop_index(op.f('ix_calls_outcome'), table_name='calls')
    op.drop_index(op.f('ix_calls_customer_id'), table_name='calls')
    op.drop_index('ix_calls_business_started', table_name='calls')
    op.drop_index('ix_calls_business_outcome', table_name='calls')
    op.drop_index(op.f('ix_calls_business_id'), table_name='calls')
    op.drop_table('calls')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('ix_users_business_role', table_name='users')
    op.drop_index(op.f('ix_users_business_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_staff_members_business_id'), table_name='staff_members')
    op.drop_index('ix_staff_business_active', table_name='staff_members')
    op.drop_table('staff_members')
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.drop_index(op.f('ix_customers_business_id'), table_name='customers')
    op.drop_index('ix_customers_business_created', table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_calendar_credentials_business_id'), table_name='calendar_credentials')
    op.drop_table('calendar_credentials')
    op.drop_index(op.f('ix_appointment_types_business_id'), table_name='appointment_types')
    op.drop_table('appointment_types')
    op.drop_index(op.f('ix_businesses_vapi_assistant_id'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_slug'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_phone_number'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_is_active'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_business_type'), table_name='businesses')
    op.drop_table('businesses')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_business_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_index('ix_audit_business_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
