"""waitlist entries

Revision ID: 3f76e4258eac
Revises: 80a57c53a343
Create Date: 2026-08-10 17:44:03.139783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types are rendered by autogenerate as app.db.models.<Type>,
# but the import is not emitted. Without this, every migration that touches a
# timestamp column fails with NameError: name 'app' is not defined.
import app.db.models


# revision identifiers, used by Alembic.
revision: str = '3f76e4258eac'
down_revision: Union[str, Sequence[str], None] = '80a57c53a343'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waitlist_entries',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('business_id', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.String(length=32), nullable=False),
    sa.Column('staff_member_id', sa.String(length=32), nullable=True),
    sa.Column('preferred_from', app.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('preferred_to', app.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notified_at', app.db.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_member_id'], ['staff_members.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_waitlist_business_status', 'waitlist_entries', ['business_id', 'status'], unique=False)
    op.create_index(op.f('ix_waitlist_entries_business_id'), 'waitlist_entries', ['business_id'], unique=False)
    op.create_index(op.f('ix_waitlist_entries_customer_id'), 'waitlist_entries', ['customer_id'], unique=False)
    op.create_index(op.f('ix_waitlist_entries_status'), 'waitlist_entries', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_waitlist_entries_status'), table_name='waitlist_entries')
    op.drop_index(op.f('ix_waitlist_entries_customer_id'), table_name='waitlist_entries')
    op.drop_index(op.f('ix_waitlist_entries_business_id'), table_name='waitlist_entries')
    op.drop_index('ix_waitlist_business_status', table_name='waitlist_entries')
    op.drop_table('waitlist_entries')
    # ### end Alembic commands ###
