"""handoff, owner notifications, daily summary, waitlist

Revision ID: 80a57c53a343
Revises: 3005a59fe145
Create Date: 2026-08-10 17:01:38.729011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types are rendered by autogenerate as app.db.models.<Type>,
# but the import is not emitted. Without this, every migration that touches a
# timestamp column fails with NameError: name 'app' is not defined.
import app.db.models


# revision identifiers, used by Alembic.
revision: str = '80a57c53a343'
down_revision: Union[str, Sequence[str], None] = '3005a59fe145'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('handoff_enabled', sa.Boolean(), server_default=sa.true(), nullable=False))
    op.add_column('businesses', sa.Column('handoff_phone', sa.String(length=32), server_default='', nullable=False))
    op.add_column('businesses', sa.Column('owner_notify_phone', sa.String(length=32), server_default='', nullable=False))
    op.add_column('businesses', sa.Column('notify_on_booking', sa.Boolean(), server_default=sa.true(), nullable=False))
    op.add_column('businesses', sa.Column('daily_summary_enabled', sa.Boolean(), server_default=sa.true(), nullable=False))
    op.add_column('businesses', sa.Column('daily_summary_hour', sa.Integer(), server_default=sa.text('9'), nullable=False))
    op.add_column('businesses', sa.Column('last_daily_summary_on', sa.String(length=10), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'last_daily_summary_on')
    op.drop_column('businesses', 'daily_summary_hour')
    op.drop_column('businesses', 'daily_summary_enabled')
    op.drop_column('businesses', 'notify_on_booking')
    op.drop_column('businesses', 'owner_notify_phone')
    op.drop_column('businesses', 'handoff_phone')
    op.drop_column('businesses', 'handoff_enabled')
    # ### end Alembic commands ###
