"""calendar auth mode

Revision ID: 83292a83e66f
Revises: 3f76e4258eac
Create Date: 2026-08-10 21:46:49.024188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types are rendered by autogenerate as app.db.models.<Type>,
# but the import is not emitted. Without this, every migration that touches a
# timestamp column fails with NameError: name 'app' is not defined.
import app.db.models


# revision identifiers, used by Alembic.
revision: str = '83292a83e66f'
down_revision: Union[str, Sequence[str], None] = '3f76e4258eac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar_credentials', sa.Column('auth_mode', sa.String(length=20), server_default='oauth', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calendar_credentials', 'auth_mode')
    # ### end Alembic commands ###
